version: '2'
services:
  server:
    build: ./server
    ports:
      - '3001:3001'
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile-prod
    ports:
      - '3000:80'
  reverse-proxy:
    image: nginx
    volumes:
     - ./prod-setup/proxy_servers.template:/etc/nginx/conf.d/mysite.template
     - /etc/letsencrypt:/etc/ssl:ro
    ports:
     - "80:80"
     - "443:443"
    network_mode: "host"
    environment:
     - NGINX_CLIENT_HOST=chess.siggame.io
     - NGINX_SERVER_HOST=chess-server.siggame.io
    command: >
        /bin/bash -c "envsubst
        '$$NGINX_CLIENT_HOST $$NGINX_SERVER_HOST'
        < /etc/nginx/conf.d/mysite.template >
        /etc/nginx/conf.d/default.conf
        && nginx -g 'daemon off;'"
